title: Cameron Leeds
description: Experienced in automating onboarding processes, focusing on data migration. A great team player and self-starter. Willing to work on traditional scrum teams and individually. Seeking a role where I can continue to learn and grow as an individual contributor and team leader. In my free time, I enjoy giving back to the community by educating, planting, and cleaning up green spaces around Atlanta through Trees Atlanta.
show_downloads: true
google_analytics:
theme: jekyll-theme-midnight
