title: Cameron Leeds
description: An adaptable manager and dedicated contributor with experience in a vast array of technologies using Agile and DevOps methodologies.
show_downloads: true
google_analytics:
theme: jekyll-theme-midnight
